const lessonData = {
    "01_AlfaRomeo.mp3": [{
        text: `Alfa Romeo is a brand that represents passion and beautiful Italian design. It was started in Milan and quickly became famous for winning many races. In fact, many people say that you are not a "true" car enthusiast until you have owned an Alfa Romeo. One of their most popular cars was the Alfasud, which was a small and fun car to drive. Today, they are famous for the Giulia, which is a very fast and elegant sedan. Alfa Romeo cars are known for their "Cuore Sportivo" or sporting heart. Drivers love them because they feel very alive and handle the road perfectly. Even though they have had some problems with reliability in the past, their style is so unique that people continue to love them. They are a symbol of Italian pride and high-performance engineering.`,
        dict: { "represents": "temsil eder", "passion": "tutku", "beautiful": "güzel", "Italian": "İtalyan", "design": "tasarım", "started": "başladı", "quickly": "hızlıca", "became": "oldu", "famous": "ünlü", "winning": "kazanma", "many": "birçok", "races": "yarışlar", "say": "söyler", "true": "gerçek", "enthusiast": "tutkun", "until": "kadar", "owned": "sahip olmak", "popular": "popüler", "small": "küçük", "fun": "eğlenceli", "drive": "sürmek", "Today": "bugün", "fast": "hızlı", "elegant": "zarif", "known": "bilinen", "sporting": "sportif", "heart": "kalp", "Drivers": "sürücüler", "love": "sever", "feel": "hissetmek", "alive": "canlı", "handle": "kavramak/idare etmek", "road": "yol", "perfectly": "kusursuzca", "Even though": "olmasına rağmen", "had": "sahipti", "some": "bazı", "problems": "sorunlar", "reliability": "güvenilirlik", "past": "geçmiş", "style": "stil", "unique": "eşsiz", "continue": "devam etmek", "symbol": "sembol", "pride": "gurur", "high-performance": "yüksek performanslı", "engineering": "mühendislik" },
        questions: [ {q:"Where was Alfa Romeo started?", a_en:"Milan", a_tr:"Milano"}, {q:"What does Cuore Sportivo mean?", a_en:"Sporting heart", a_tr:"Sportif kalp"}, {q:"Are they famous for winning races?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the Alfasud a small car?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Giulia a fast sedan?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they have reliability problems in the past?", a_en:"Yes", a_tr:"Evet"}, {q:"Is Alfa Romeo a symbol of Italian pride?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "02_AstonMartin.mp3": [{
        text: `Aston Martin is the ultimate brand for luxury and sophistication. This British company is most famous for being the favorite car of the secret agent James Bond. When you see an Aston Martin, you think of power and high-class style. Their cars are often built by hand and use the finest materials, like soft leather and real wood. The DB5 is perhaps their most famous historic model, but today they make amazing cars like the Vantage and the DB11. They are known for having very powerful V12 engines that make a wonderful sound. An Aston Martin is not just a car; it is a piece of art that you can drive very fast. It represents the best of British engineering and the dream of living like a movie star.`,
        dict: { "ultimate": "nihai/en üst", "luxury": "lüks", "sophistication": "sofistike olma", "British": "İngiliz", "company": "şirket", "famous": "ünlü", "favorite": "favori", "secret": "gizli", "agent": "ajan", "see": "görmek", "think": "düşünmek", "power": "güç", "high-class": "yüksek sınıf", "style": "stil", "often": "sık sık", "built": "inşa edilmiş/yapılmış", "hand": "el", "use": "kullanmak", "finest": "en iyi", "materials": "malzemeler", "soft": "yumuşak", "leather": "deri", "real": "gerçek", "wood": "ahşap", "perhaps": "belki", "historic": "tarihi", "model": "model", "today": "bugün", "make": "yapmak", "amazing": "şaşırtıcı/harika", "known": "bilinen", "having": "sahip olmak", "powerful": "güçlü", "engines": "motorlar", "wonderful": "harika", "sound": "ses", "just": "sadece", "piece": "parça", "art": "sanat", "drive": "sürmek", "fast": "hızlı", "represents": "temsil eder", "best": "en iyi", "engineering": "mühendislik", "dream": "rüya", "living": "yaşamak", "movie": "film", "star": "yıldız" },
        questions: [ {q:"Is Aston Martin a British company?", a_en:"Yes", a_tr:"Evet"}, {q:"Who is the famous secret agent?", a_en:"James Bond", a_tr:"James Bond"}, {q:"Are their cars built by hand?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they use soft leather?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the DB5 a historic model?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they have V12 engines?", a_en:"Yes", a_tr:"Evet"}, {q:"Is it compared to a piece of art?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "03_Audi.mp3": [{
        text: `Audi is a German luxury brand that is famous for its technology and high quality. Their slogan is "Vorsprung durch Technik," which means "Progress through Technology." Audi became very popular in the 1980s because of their "Quattro" system. This is a special all-wheel-drive system that allows the car to have great grip on rain, snow, or mud. This technology helped Audi win many rally championships. Today, Audi is known for making very comfortable and modern cars like the A4 and the Q5 SUV. Their interiors are famous for being very clean and full of high-tech screens. Audi is a perfect choice for people who want a car that is both fast and very safe to drive in all types of weather.`,
        dict: { "German": "Alman", "luxury": "lüks", "technology": "teknoloji", "high": "yüksek", "quality": "kalite", "slogan": "slogan", "means": "anlamına gelir", "Progress": "ilerleme", "through": "yoluyla/aracılığıyla", "became": "oldu", "popular": "popüler", "because": "çünkü", "special": "özel", "all-wheel-drive": "dört çeker", "system": "sistem", "allows": "izin verir", "great": "harika", "grip": "kavrama/tutuş", "rain": "yağmur", "snow": "kar", "mud": "çamur", "helped": "yardım etti", "win": "kazanmak", "many": "birçok", "rally": "rali", "championships": "şampiyonalar", "Today": "bugün", "known": "bilinen", "making": "yapmak", "comfortable": "rahat", "modern": "modern", "interiors": "iç mekanlar", "clean": "temiz", "full": "dolu", "high-tech": "yüksek teknoloji", "screens": "ekranlar", "perfect": "mükemmel", "choice": "seçim", "want": "istemek", "both": "her ikisi", "fast": "hızlı", "safe": "güvenli", "drive": "sürmek", "types": "türler", "weather": "hava" },
        questions: [ {q:"Is Audi a German brand?", a_en:"Yes", a_tr:"Evet"}, {q:"What does their slogan mean?", a_en:"Progress through Technology", a_tr:"Teknoloji ile İlerleme"}, {q:"What is their all-wheel-drive system called?", a_en:"Quattro", a_tr:"Quattro"}, {q:"Does Quattro help in snow?", a_en:"Yes", a_tr:"Evet"}, {q:"Are their cars comfortable?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they have high-tech screens?", a_en:"Yes", a_tr:"Evet"}, {q:"Is Audi safe in all types of weather?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "04_BMW.mp3": [{
        text: `BMW stands for "Bayerische Motoren Werke" and is known worldwide as the maker of the "Ultimate Driving Machine." This brand focuses on the driver. BMW cars are designed to be sporty and precise. Their most famous car is the 3 Series, which has been a best-seller for decades because it is practical but also very fun to drive. BMW is also famous for its "M" division, which takes normal cars and makes them incredibly fast for the race track. The brand has a very recognizable front "grille" that looks like two kidneys. Whether it is a small hatchback or a large SUV, a BMW is always built for people who love the feeling of driving and want high German quality.`,
        dict: { "stands for": "anlamına gelir", "known": "bilinen", "worldwide": "dünya çapında", "maker": "üretici", "Ultimate": "nihai/en üstün", "Driving": "sürüş", "Machine": "makine", "focuses": "odaklanır", "driver": "sürücü", "designed": "tasarlanmış", "sporty": "sportif", "precise": "kesin/hassas", "famous": "ünlü", "best-seller": "en çok satan", "decades": "on yıllar", "because": "çünkü", "practical": "pratik", "also": "ayrıca", "fun": "eğlenceli", "drive": "sürmek", "division": "bölüm", "takes": "alır", "normal": "normal", "makes": "yapar", "incredibly": "inanılmaz derecede", "fast": "hızlı", "race": "yarış", "track": "pist", "recognizable": "tanınabilir", "front": "ön", "grille": "ızgara", "looks like": "gibi görünür", "two": "iki", "kidneys": "böbrekler", "Whether": "olsa da/olup olmadığı", "small": "küçük", "large": "büyük", "always": "her zaman", "built": "yapılmış/inşa edilmiş", "love": "sever", "feeling": "his/duygu", "want": "istemek", "high": "yüksek", "German": "Alman", "quality": "kalite" },
        questions: [ {q:"What does BMW stand for?", a_en:"Bayerische Motoren Werke", a_tr:"Bayerische Motoren Werke"}, {q:"Is BMW known as the Ultimate Driving Machine?", a_en:"Yes", a_tr:"Evet"}, {q:"What is their most famous car?", a_en:"3 Series", a_tr:"3 Serisi"}, {q:"Is the 3 Series fun to drive?", a_en:"Yes", a_tr:"Evet"}, {q:"What division makes them fast?", a_en:"M division", a_tr:"M bölümü"}, {q:"What does the front grille look like?", a_en:"Two kidneys", a_tr:"İki böbrek"}, {q:"Do they build large SUVs?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "05_Cadillac.mp3": [{
        text: `Cadillac is the most famous luxury brand in American history. For many years, it was known as the "Standard of the World" because it was the first company to use interchangeable parts. This was a massive innovation in engineering. In the 1950s and 60s, Cadillacs were very large cars with "fins" on the back that looked like rockets. They were a symbol of the American Dream and were owned by famous people like Elvis Presley. Today, Cadillac is famous for making the Escalade, which is a massive and very comfortable SUV. They also make fast sedans that compete with the best German cars. Cadillac represents the American idea of "bigger is better" and provides a very smooth and quiet ride for its passengers.`,
        dict: { "most": "en", "famous": "ünlü", "luxury": "lüks", "American": "Amerikan", "history": "tarih", "many": "birçok", "years": "yıllar", "known": "bilinen", "Standard": "standart", "World": "dünya", "because": "çünkü", "first": "ilk", "company": "şirket", "use": "kullanmak", "interchangeable": "değiştirilebilir", "parts": "parçalar", "massive": "muazzam", "innovation": "yenilik", "engineering": "mühendislik", "very": "çok", "large": "büyük", "fins": "yüzgeçler/kuyruklar", "back": "arka", "looked like": "gibi görünüyordu", "rockets": "roketler", "symbol": "sembol", "Dream": "rüya", "owned": "sahip olunan", "Today": "bugün", "making": "yapmak", "comfortable": "rahat", "also": "ayrıca", "make": "yapmak", "fast": "hızlı", "sedans": "sedanlar", "compete": "rekabet etmek", "best": "en iyi", "German": "Alman", "represents": "temsil eder", "idea": "fikir", "bigger": "daha büyük", "better": "daha iyi", "provides": "sağlar", "smooth": "pürüzsüz", "quiet": "sessiz", "ride": "sürüş", "passengers": "yolcular" },
        questions: [ {q:"Is Cadillac an American brand?", a_en:"Yes", a_tr:"Evet"}, {q:"Were they called the Standard of the World?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use interchangeable parts?", a_en:"Yes", a_tr:"Evet"}, {q:"What did the fins look like?", a_en:"Rockets", a_tr:"Roketler"}, {q:"Did Elvis Presley own a Cadillac?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Escalade a massive SUV?", a_en:"Yes", a_tr:"Evet"}, {q:"Does Cadillac represent bigger is better?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "06_Chevrolet.mp3": [{
        text: `Chevrolet, often called "Chevy," is one of the biggest and most popular American car brands. It was started by a Swiss race car driver and became part of General Motors. Chevy is famous for making cars for everyone. They make the Silverado, which is one of the best-selling trucks in the world and is used by millions of workers. They also make the Corvette, which is a legendary sports car that can go as fast as a Ferrari but costs much less money. For families, they have popular cars like the Malibu and the Equinox. Chevrolet is a brand that people trust for being dependable and strong. It is a true part of American culture and can be found in almost every town in the USA.`,
        dict: { "often": "sık sık", "called": "adlandırılan", "biggest": "en büyük", "popular": "popüler", "American": "Amerikan", "brands": "markalar", "started": "başlatıldı", "Swiss": "İsviçreli", "race": "yarış", "driver": "sürücü", "became": "oldu", "part": "parça", "famous": "ünlü", "making": "yapmak", "everyone": "herkes", "make": "yapmak", "best-selling": "en çok satan", "trucks": "kamyonlar", "world": "dünya", "used": "kullanılan", "millions": "milyonlarca", "workers": "işçiler", "also": "ayrıca", "legendary": "efsanevi", "sports": "spor", "go": "gitmek", "fast": "hızlı", "costs": "mal olur", "much": "çok", "less": "daha az", "money": "para", "families": "aileler", "have": "sahip olmak", "trust": "güvenmek", "dependable": "güvenilir", "strong": "güçlü", "true": "gerçek", "culture": "kültür", "can be found": "bulunabilir", "almost": "neredeyse", "every": "her", "town": "kasaba" },
        questions: [ {q:"Is Chevrolet often called Chevy?", a_en:"Yes", a_tr:"Evet"}, {q:"Was it started by a Swiss driver?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Silverado a popular truck?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Corvette a sports car?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the Corvette cost less than a Ferrari?", a_en:"Yes", a_tr:"Evet"}, {q:"Do people trust Chevy to be strong?", a_en:"Yes", a_tr:"Evet"}, {q:"Can you find Chevy in almost every town?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "07_Citroen.mp3": [{
        text: `Citroën is a French brand that is famous for being different and creative. Throughout history, they have made cars with very strange and clever engineering. Their most famous car is the 2CV, which was built to be a simple and cheap car for French farmers. It was so soft that it could carry a basket of eggs across a bumpy field without breaking any. Another famous car was the DS, which looked like a spaceship and had a special "suspension" that made the car feel like it was floating on air. Today, Citroën continues to make cars that look very modern and unique. They focus on comfort and style. Citroën is a brand for people who do not want a boring car and appreciate French art and innovation.`,
        dict: { "French": "Fransız", "famous": "ünlü", "different": "farklı", "creative": "yaratıcı", "Throughout": "boyunca", "history": "tarih", "made": "yaptı", "strange": "garip", "clever": "zeki/akıllıca", "engineering": "mühendislik", "built": "inşa edildi", "simple": "basit", "cheap": "ucuz", "farmers": "çiftçiler", "soft": "yumuşak", "carry": "taşımak", "basket": "sepet", "eggs": "yumurtalar", "across": "karşıdan karşıya", "bumpy": "engebeli", "field": "tarla/alan", "without": "olmaksızın", "breaking": "kırmak", "any": "hiç", "Another": "başka bir", "looked like": "gibi görünüyordu", "spaceship": "uzay gemisi", "had": "sahipti", "special": "özel", "suspension": "süspansiyon", "made": "yaptı", "feel like": "gibi hissetmek", "floating": "süzülmek/yüzmek", "air": "hava", "Today": "bugün", "continues": "devam ediyor", "make": "yapmak", "look": "görünmek", "modern": "modern", "unique": "eşsiz", "focus": "odaklanmak", "comfort": "konfor", "style": "stil", "do not want": "istememek", "boring": "sıkıcı", "appreciate": "takdir etmek", "art": "sanat", "innovation": "yenilik" },
        questions: [ {q:"Is Citroën a French brand?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they famous for being creative?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the 2CV built for farmers?", a_en:"Yes", a_tr:"Evet"}, {q:"Could it carry eggs without breaking?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the DS look like a spaceship?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they focus on comfort?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they make boring cars?", a_en:"No", a_tr:"Hayır"} ]
    }],
    "08_Ferrari.mp3": [{
        text: `Ferrari is probably the most famous car brand in the entire world. It was started by Enzo Ferrari, who only wanted to build race cars. The famous "Prancing Horse" logo is a symbol of speed, wealth, and exclusivity. Ferrari cars are almost always red and are known for their incredible V12 and V8 engines. They are very expensive and very fast. To own a Ferrari is a dream for millions of people. Ferrari is also the most successful team in Formula 1 racing history. They do not make many cars each year because they want to keep them special. When you see a Ferrari on the street, everyone stops to look. It is the ultimate Italian supercar and a masterpiece of performance.`,
        dict: { "probably": "muhtemelen", "most": "en", "famous": "ünlü", "entire": "tüm/bütün", "world": "dünya", "started": "başlatıldı", "only": "sadece", "wanted": "istedi", "build": "inşa etmek", "race": "yarış", "Prancing": "şaha kalkan", "Horse": "at", "logo": "logo", "symbol": "sembol", "speed": "hız", "wealth": "zenginlik", "exclusivity": "ayrıcalık", "almost": "neredeyse", "always": "her zaman", "red": "kırmızı", "known": "bilinen", "incredible": "inanılmaz", "engines": "motorlar", "expensive": "pahalı", "fast": "hızlı", "own": "sahip olmak", "dream": "rüya", "millions": "milyonlarca", "people": "insanlar", "successful": "başarılı", "team": "takım", "racing": "yarış", "history": "tarih", "do not make": "yapmazlar", "many": "birçok/fazla", "each": "her", "year": "yıl", "because": "çünkü", "keep": "tutmak", "special": "özel", "see": "görmek", "street": "sokak", "everyone": "herkes", "stops": "durur", "look": "bakmak", "ultimate": "nihai", "Italian": "İtalyan", "supercar": "süper araba", "masterpiece": "şaheser", "performance": "performans" },
        questions: [ {q:"Did Enzo Ferrari want to build race cars?", a_en:"Yes", a_tr:"Evet"}, {q:"What is their logo?", a_en:"Prancing Horse", a_tr:"Şaha Kalkan At"}, {q:"Are Ferrari cars usually red?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they cheap to buy?", a_en:"No", a_tr:"Hayır"}, {q:"Are they successful in Formula 1?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they make many cars each year?", a_en:"No", a_tr:"Hayır"}, {q:"Is a Ferrari a masterpiece of performance?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "09_Ford.mp3": [{
        text: `Ford is the company that changed the world forever. Henry Ford created the "Model T," which was the first car that normal people could afford to buy. He used the "assembly line" to build cars very quickly. This started the modern industrial world. Ford is also responsible for the "Mustang," which is a legendary "pony car" that became a symbol of freedom and cool style in the 1960s. Today, Ford’s F-150 truck is the most popular vehicle in America. They are also moving into the future with electric cars like the Mustang Mach-E. Ford is a brand that represents hard work and history. It is a company that put the whole world on wheels and continues to be a leader in the industry.`,
        dict: { "company": "şirket", "changed": "değiştirdi", "world": "dünya", "forever": "sonsuza dek", "created": "yarattı", "first": "ilk", "normal": "normal", "people": "insanlar", "afford": "gücü yetmek (maddi)", "buy": "satın almak", "used": "kullandı", "assembly line": "montaj hattı", "build": "inşa etmek/yapmak", "quickly": "hızlıca", "started": "başlattı", "modern": "modern", "industrial": "endüstriyel", "responsible": "sorumlu", "legendary": "efsanevi", "became": "oldu", "symbol": "sembol", "freedom": "özgürlük", "cool": "havalı", "style": "stil", "Today": "bugün", "popular": "popüler", "vehicle": "araç", "moving": "ilerliyor", "future": "gelecek", "electric": "elektrikli", "represents": "temsil eder", "hard": "sıkı", "work": "çalışma", "history": "tarih", "put": "koydu", "whole": "bütün", "wheels": "tekerlekler", "continues": "devam ediyor", "leader": "lider", "industry": "endüstri" },
        questions: [ {q:"Did Ford change the world forever?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the Model T for normal people?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Henry Ford use the assembly line?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Mustang a pony car?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the F-150 popular in America?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Mustang Mach-E electric?", a_en:"Yes", a_tr:"Evet"}, {q:"Does Ford represent hard work?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "10_Honda.mp3": [{
        text: `Honda is a Japanese brand that is famous for its incredible engineering. It started by making motorcycles and then moved to cars. Honda engines are known for being some of the best and most reliable in the world. They rarely break down, and they are very efficient with fuel. The Honda Civic and the Honda Accord are two of the best-selling cars in history because they are perfect for families and students. Honda also makes very fast cars like the Civic Type R and the NSX supercar. Honda is a brand for people who want a smart car that is easy to own and lasts for a very long time. They are also leaders in making robots and airplane engines, showing that they are a true technology company.`,
        dict: { "Japanese": "Japon", "famous": "ünlü", "incredible": "inanılmaz", "engineering": "mühendislik", "started": "başladı", "making": "yapmak", "motorcycles": "motosikletler", "moved": "geçti/taşındı", "engines": "motorlar", "known": "bilinen", "best": "en iyi", "reliable": "güvenilir", "world": "dünya", "rarely": "nadiren", "break down": "bozulmak", "efficient": "verimli", "fuel": "yakıt", "two": "iki", "best-selling": "en çok satan", "history": "tarih", "because": "çünkü", "perfect": "mükemmel", "families": "aileler", "students": "öğrenciler", "makes": "yapar", "fast": "hızlı", "smart": "akıllı", "easy": "kolay", "own": "sahip olmak", "lasts": "sürer/dayanır", "long": "uzun", "time": "zaman", "leaders": "liderler", "robots": "robotlar", "airplane": "uçak", "showing": "gösteren", "true": "gerçek", "technology": "teknoloji", "company": "şirket" },
        questions: [ {q:"Is Honda a Japanese brand?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they start by making motorcycles?", a_en:"Yes", a_tr:"Evet"}, {q:"Are Honda engines reliable?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they break down often?", a_en:"No", a_tr:"Hayır"}, {q:"Are the Civic and Accord for families?", a_en:"Yes", a_tr:"Evet"}, {q:"Does Honda make robots?", a_en:"Yes", a_tr:"Evet"}, {q:"Do their cars last a long time?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "11_Jaguar.mp3": [{
        text: `Jaguar is a British brand that is famous for three things: "Grace, Space, and Pace." This means their cars are beautiful, comfortable, and very fast. In the 1960s, they made the E-Type, which many people say is the most beautiful car ever built. Even Enzo Ferrari said it was beautiful! Jaguar cars have a very classic and elegant look that makes them stand out from other luxury cars. They are known for their smooth engines and high-quality interiors with lots of wood and leather. Today, Jaguar makes fast sedans and also electric SUVs like the I-PACE. Jaguar is a brand for people who want a luxury car with a lot of character and a long history of British racing success.`,
        dict: { "British": "İngiliz", "famous": "ünlü", "three": "üç", "things": "şeyler", "Grace": "zarafet", "Space": "genişlik", "Pace": "hız/tempo", "means": "anlamına gelir", "beautiful": "güzel", "comfortable": "rahat", "fast": "hızlı", "made": "yaptı", "many": "birçok", "say": "söyler", "ever": "şimdiye kadar", "built": "yapılmış/inşa edilmiş", "Even": "hatta", "classic": "klasik", "elegant": "zarif", "look": "görünüm", "makes": "yapar", "stand out": "öne çıkmak", "other": "diğer", "luxury": "lüks", "known": "bilinen", "smooth": "pürüzsüz", "engines": "motorlar", "high-quality": "yüksek kaliteli", "interiors": "iç mekanlar", "lots of": "birçok", "wood": "ahşap", "leather": "deri", "Today": "bugün", "sedans": "sedanlar", "electric": "elektrikli", "want": "istemek", "lot of": "çok", "character": "karakter", "long": "uzun", "history": "tarih", "racing": "yarış", "success": "başarı" },
        questions: [ {q:"Is Jaguar a British brand?", a_en:"Yes", a_tr:"Evet"}, {q:"Does Pace mean fast?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Enzo Ferrari like the E-Type?", a_en:"Yes", a_tr:"Evet"}, {q:"Do Jaguar cars look elegant?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they use wood and leather?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the I-PACE an electric SUV?", a_en:"Yes", a_tr:"Evet"}, {q:"Does Jaguar have racing success?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "12_Lamborghini.mp3": [{
        text: `Lamborghini was started because of an argument! Ferruccio Lamborghini was a rich tractor builder who owned a Ferrari. He thought the Ferrari had a bad clutch and told Enzo Ferrari about it. Enzo told him to stick to tractors, so Ferruccio decided to build his own supercar to beat Ferrari. Lamborghini cars are famous for being "wild" and "crazy." They have very sharp designs and doors that open upwards like scissors. The Countach and the Diablo are legendary cars that were on the posters of every child's bedroom in the 80s and 90s. Today, they make the Aventador and the Urus SUV. A Lamborghini is loud, fast, and impossible to ignore. It is a brand for people who want to be noticed and love extreme performance.`,
        dict: { "started": "başladı", "because": "çünkü", "argument": "tartışma", "rich": "zengin", "tractor": "traktör", "builder": "üretici/inşaatçı", "owned": "sahipti", "thought": "düşündü", "bad": "kötü", "clutch": "debriyaj", "told": "söyledi", "stick": "bağlı kalmak/yapışmak", "decided": "karar verdi", "build": "yapmak/inşa etmek", "own": "kendi", "supercar": "süper araba", "beat": "yenmek", "famous": "ünlü", "wild": "vahşi", "crazy": "çılgın", "sharp": "keskin", "designs": "tasarımlar", "doors": "kapılar", "open": "açılır", "upwards": "yukarıya doğru", "scissors": "makas", "legendary": "efsanevi", "posters": "posterler", "child": "çocuk", "bedroom": "yatak odası", "Today": "bugün", "make": "yapmak", "loud": "gürültülü", "fast": "hızlı", "impossible": "imkansız", "ignore": "görmezden gelmek", "want": "istemek", "noticed": "fark edilmek", "love": "sevmek", "extreme": "aşırı", "performance": "performans" },
        questions: [ {q:"Was Lamborghini started after an argument?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Ferruccio build tractors first?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he want to beat Ferrari?", a_en:"Yes", a_tr:"Evet"}, {q:"Are the cars wild and crazy?", a_en:"Yes", a_tr:"Evet"}, {q:"Do the doors open like scissors?", a_en:"Yes", a_tr:"Evet"}, {q:"Are Lamborghini cars quiet?", a_en:"No", a_tr:"Hayır"}, {q:"Is it impossible to ignore them?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "13_Mazda.mp3": [{
        text: `Mazda is a Japanese brand that likes to do things differently. They are famous for the "Rotary Engine," which is a special type of engine that is very small but very powerful. They used this engine to win the famous 24 Hours of Le Mans race. Mazda is also the maker of the MX-5 Miata, which is the best-selling two-seat sports car in history. The Miata is loved because it is simple, light, and very fun to drive on a sunny day. Mazda cars are known for their "Kodo" design, which makes them look like they are moving even when they are standing still. Mazda is a brand for people who love the "soul of motion" and want a car that feels connected to the driver.`,
        dict: { "Japanese": "Japon", "likes": "sever", "do": "yapmak", "things": "şeyler", "differently": "farklı bir şekilde", "famous": "ünlü", "special": "özel", "type": "tür", "engine": "motor", "small": "küçük", "powerful": "güçlü", "used": "kullandı", "win": "kazanmak", "race": "yarış", "maker": "üretici", "best-selling": "en çok satan", "two-seat": "iki koltuklu", "sports": "spor", "history": "tarih", "loved": "sevilen", "because": "çünkü", "simple": "basit", "light": "hafif", "fun": "eğlenceli", "drive": "sürmek", "sunny": "güneşli", "day": "gün", "known": "bilinen", "design": "tasarım", "makes": "yapar", "look like": "gibi görünmek", "moving": "hareket eden", "even": "bile", "standing": "duran", "still": "hareketsiz", "love": "sevmek", "soul": "ruh", "motion": "hareket", "want": "istemek", "feels": "hisseder", "connected": "bağlı", "driver": "sürücü" },
        questions: [ {q:"Is Mazda a Japanese brand?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Rotary engine very small?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they win Le Mans with it?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Miata a two-seat car?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Miata heavy or light?", a_en:"Light", a_tr:"Hafif"}, {q:"Does Kodo design look like motion?", a_en:"Yes", a_tr:"Evet"}, {q:"Do drivers feel connected?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "14_MercedesBenz.mp3": [{
        text: `Mercedes-Benz is the brand that started it all. Karl Benz invented the first gasoline-powered car in 1886. Since then, Mercedes-Benz has been the global standard for luxury and safety. They were the first to use many things we have in cars today, like airbags and ABS brakes. A Mercedes is a symbol of success and high quality. They make everything from small city cars to the massive G-Wagon and the luxury S-Class, which is often used by world leaders. Mercedes-Benz cars are famous for being very solid and comfortable. When you close the door of a Mercedes, it sounds like a bank vault. It is a brand for people who want the very best in German luxury and the latest technology.`,
        dict: { "started": "başlattı", "invented": "icat etti", "first": "ilk", "gasoline-powered": "benzinle çalışan", "Since then": "o zamandan beri", "global": "küresel", "standard": "standart", "luxury": "lüks", "safety": "güvenlik", "use": "kullanmak", "many": "birçok", "things": "şeyler", "have": "sahip olmak", "today": "bugün", "airbags": "hava yastıkları", "brakes": "frenler", "symbol": "sembol", "success": "başarı", "high": "yüksek", "quality": "kalite", "make": "yapmak", "everything": "her şey", "small": "küçük", "city": "şehir", "massive": "muazzam", "often": "sık sık", "used": "kullanılan", "world": "dünya", "leaders": "liderler", "famous": "ünlü", "solid": "sağlam", "comfortable": "rahat", "close": "kapatmak", "door": "kapı", "sounds like": "gibi ses çıkarır", "bank": "banka", "vault": "kasa", "want": "istemek", "best": "en iyi", "German": "Alman", "latest": "en son", "technology": "teknoloji" },
        questions: [ {q:"Did Karl Benz invent the first gasoline car?", a_en:"Yes", a_tr:"Evet"}, {q:"Is Mercedes a symbol of safety?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use airbags first?", a_en:"Yes", a_tr:"Evet"}, {q:"Do world leaders use the S-Class?", a_en:"Yes", a_tr:"Evet"}, {q:"Are their cars solid and comfortable?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the door sound like a bank vault?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they use German technology?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "15_Nissan.mp3": [{
        text: `Nissan is a Japanese brand that is known for being a great innovator. They were one of the first companies to make a mass-market electric car, the Nissan Leaf. They are also famous for their sports cars, like the "Z" series and the legendary Skyline GT-R. The GT-R is nicknamed "Godzilla" because it is so fast and powerful that it can beat much more expensive supercars. Nissan also makes very popular and tough trucks and SUVs like the Patrol and the Qashqai. Nissan is a brand that offers a great mix of practical family cars and exciting performance cars. They have a long history of making cars that are advanced but also accessible to many people around the world.`,
        dict: { "Japanese": "Japon", "known": "bilinen", "great": "harika", "innovator": "yenilikçi", "first": "ilk", "companies": "şirketler", "make": "yapmak", "mass-market": "kitle pazarı", "electric": "elektrikli", "also": "ayrıca", "famous": "ünlü", "sports": "spor", "legendary": "efsanevi", "nicknamed": "lakaplı", "because": "çünkü", "fast": "hızlı", "powerful": "güçlü", "beat": "yenmek", "much": "çok", "expensive": "pahalı", "supercars": "süper arabalar", "makes": "yapar", "popular": "popüler", "tough": "zorlu/dayanıklı", "trucks": "kamyonlar", "offers": "sunar", "mix": "karışım", "practical": "pratik", "family": "aile", "exciting": "heyecan verici", "performance": "performans", "long": "uzun", "history": "tarih", "making": "yapmak", "advanced": "gelişmiş", "accessible": "erişilebilir", "many": "birçok", "people": "insanlar", "around": "etrafında", "world": "dünya" },
        questions: [ {q:"Is Nissan known as a great innovator?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the Leaf an electric car?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the GT-R nicknamed Godzilla?", a_en:"Yes", a_tr:"Evet"}, {q:"Can it beat expensive supercars?", a_en:"Yes", a_tr:"Evet"}, {q:"Are Nissan trucks tough?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they make practical family cars?", a_en:"Yes", a_tr:"Evet"}, {q:"Are their cars accessible to many people?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "16_Porsche.mp3": [{
        text: `Porsche is the benchmark for sports cars. The company was started by Ferdinand Porsche, who also designed the original Volkswagen Beetle. The most famous Porsche is the 911, which has had the same basic shape for over 60 years. It has the engine in the back, which makes it very unique to drive. Porsche cars are famous for their incredible build quality; you can drive a Porsche on a race track all day and then drive it to the supermarket. They are very reliable and hold their value very well. Today, Porsche also makes very fast SUVs like the Cayenne and the Macan, and a beautiful electric car called the Taycan. Porsche is a brand for people who want perfect engineering and a car that is built to perform.`,
        dict: { "benchmark": "kriter/ölçüt", "sports": "spor", "company": "şirket", "started": "başlatıldı", "also": "ayrıca", "designed": "tasarladı", "original": "orijinal", "most": "en", "famous": "ünlü", "same": "aynı", "basic": "temel", "shape": "şekil", "over": "üzerinde/fazla", "years": "yıllar", "engine": "motor", "back": "arka", "makes": "yapar", "unique": "eşsiz", "drive": "sürmek", "incredible": "inanılmaz", "build": "yapı/inşa", "quality": "kalite", "race track": "yarış pisti", "all day": "tüm gün", "then": "sonra", "supermarket": "süpermarket", "reliable": "güvenilir", "hold": "tutmak/korumak", "value": "değer", "well": "iyi", "Today": "bugün", "fast": "hızlı", "beautiful": "güzel", "electric": "elektrikli", "called": "adlandırılan", "want": "istemek", "perfect": "mükemmel", "engineering": "mühendislik", "built": "yapılmış", "perform": "performans göstermek" },
        questions: [ {q:"Did Ferdinand Porsche design the Beetle?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the 911 the most famous Porsche?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the engine in the back?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the build quality incredible?", a_en:"Yes", a_tr:"Evet"}, {q:"Can you drive it to the supermarket?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they reliable cars?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Taycan an electric car?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "17_Subaru.mp3": [{
        text: `Subaru is a Japanese brand that is loved by people who live in the mountains or love the outdoors. They are famous for two things: the "Boxer" engine and "Symmetrical All-Wheel Drive." The Boxer engine is flat, which makes the car very stable. Almost every Subaru has all-wheel drive as standard, which makes them excellent for driving in snow and rain. Subaru is also a legend in rally racing. Their blue and gold WRX cars won many championships and became a favorite for young drivers who love speed. Subaru owners are very loyal because the cars are safe, tough, and very practical for families who go camping or skiing. It is a brand that represents adventure and dependability in difficult conditions.`,
        dict: { "Japanese": "Japon", "loved": "sevilen", "people": "insanlar", "live": "yaşamak", "mountains": "dağlar", "outdoors": "açık hava", "famous": "ünlü", "two": "iki", "things": "şeyler", "engine": "motor", "Symmetrical": "simetrik", "All-Wheel Drive": "dört tekerlekten çekiş", "flat": "düz", "makes": "yapar", "stable": "dengeli", "Almost": "neredeyse", "every": "her", "standard": "standart", "excellent": "mükemmel", "driving": "sürüş", "snow": "kar", "rain": "yağmur", "legend": "efsane", "rally": "rali", "racing": "yarış", "blue": "mavi", "gold": "altın", "won": "kazandı", "many": "birçok", "championships": "şampiyonalar", "became": "oldu", "favorite": "favori", "young": "genç", "drivers": "sürücüler", "love": "sever", "speed": "hız", "owners": "sahipler", "loyal": "sadık", "because": "çünkü", "safe": "güvenli", "tough": "zorlu/dayanıklı", "practical": "pratik", "families": "aileler", "go": "gitmek", "camping": "kamp yapmak", "skiing": "kayak yapmak", "represents": "temsil eder", "adventure": "macera", "dependability": "güvenilirlik", "difficult": "zor", "conditions": "koşullar" },
        questions: [ {q:"Is Subaru loved by people in the mountains?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Boxer engine flat?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they have all-wheel drive as standard?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they excellent in snow?", a_en:"Yes", a_tr:"Evet"}, {q:"Is Subaru a legend in rally racing?", a_en:"Yes", a_tr:"Evet"}, {q:"Are Subaru owners loyal?", a_en:"Yes", a_tr:"Evet"}, {q:"Are the cars safe and tough?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "18_Suzuki.mp3": [{
        text: `Suzuki is the master of small cars. This Japanese brand started by making weaving machines and then motorcycles before making cars. Suzuki is famous for making cars that are small, light, and very "tough." Their most famous car is the Jimny, which is a tiny 4x4 that can go through mud and mountains better than many big trucks. They also make the Swift, which is a popular and fun small car for the city. Suzuki cars are great because they are cheap to buy, cheap to run, and very easy to park. In many parts of the world, like India, Suzuki is the most popular brand because their cars are so practical. Suzuki is a brand for people who want a simple, honest, and reliable car that gets the job done.`,
        dict: { "master": "usta", "small": "küçük", "Japanese": "Japon", "started": "başladı", "making": "yapmak", "weaving": "dokuma", "machines": "makineler", "then": "sonra", "motorcycles": "motosikletler", "before": "önce", "cars": "arabalar", "famous": "ünlü", "light": "hafif", "tough": "dayanıklı", "tiny": "minik", "go": "gitmek", "through": "içinden", "mud": "çamur", "mountains": "dağlar", "better": "daha iyi", "big": "büyük", "trucks": "kamyonlar", "also": "ayrıca", "popular": "popüler", "fun": "eğlenceli", "city": "şehir", "great": "harika", "because": "çünkü", "cheap": "ucuz", "buy": "satın almak", "run": "çalıştırmak (masraf)", "easy": "kolay", "park": "park etmek", "parts": "parçalar", "world": "dünya", "most": "en", "practical": "pratik", "want": "istemek", "simple": "basit", "honest": "dürüst", "reliable": "güvenilir", "gets done": "işi halleder", "job": "iş" },
        questions: [ {q:"Is Suzuki the master of small cars?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they make weaving machines first?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Jimny a tiny 4x4?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Swift fun for the city?", a_en:"Yes", a_tr:"Evet"}, {q:"Are Suzuki cars cheap to buy?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they easy to park?", a_en:"Yes", a_tr:"Evet"}, {q:"Is Suzuki popular in India?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "19_Tesla.mp3": [{
        text: `Tesla is the newest brand on this list, but it has changed the car world more than anyone else in the last 20 years. Started by Elon Musk and others, Tesla proved that electric cars could be fast, cool, and have a long range. Their first car, the Roadster, was a sports car, but now they have the Model 3 and Model Y, which are some of the best-selling cars in the world. Tesla cars are like computers on wheels; they have massive screens and can even drive themselves on the highway using "Autopilot." Tesla also built a massive network of "Superchargers" so people can travel long distances. Tesla is the brand that forced every other car company to start making electric vehicles. It represents the future of technology and energy.`,
        dict: { "newest": "en yeni", "brand": "marka", "list": "liste", "changed": "değiştirdi", "world": "dünya", "more than": "den daha fazla", "anyone else": "başka herhangi biri", "last": "son", "years": "yıllar", "Started": "başlatıldı", "proved": "kanıtladı", "electric": "elektrikli", "fast": "hızlı", "cool": "havalı", "have": "sahip olmak", "long": "uzun", "range": "menzil", "first": "ilk", "sports": "spor", "now": "şimdi", "best-selling": "en çok satan", "like": "gibi", "computers": "bilgisayarlar", "wheels": "tekerlekler", "massive": "muazzam", "screens": "ekranlar", "even": "bile", "drive": "sürmek", "themselves": "kendileri", "highway": "otoyol", "using": "kullanarak", "built": "inşa etti", "network": "ağ", "people": "insanlar", "travel": "seyahat etmek", "distances": "mesafeler", "forced": "zorladı", "every": "her", "other": "diğer", "company": "şirket", "start": "başlamak", "making": "yapmak", "vehicles": "araçlar", "represents": "temsil eder", "future": "gelecek", "technology": "teknoloji", "energy": "enerji" },
        questions: [ {q:"Is Tesla the newest brand on the list?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Elon Musk help start Tesla?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Tesla prove electric cars can be fast?", a_en:"Yes", a_tr:"Evet"}, {q:"Are Tesla cars like computers on wheels?", a_en:"Yes", a_tr:"Evet"}, {q:"Can they drive themselves on the highway?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Tesla build Superchargers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Tesla force others to make electric cars?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "20_Toyota.mp3": [{
        text: `Toyota is currently the largest car company in the world. They are famous for one thing above all else: reliability. A Toyota car is built to last forever. Many people in Africa and the Middle East use the Toyota Hilux truck because it is almost impossible to break, even in the desert. Toyota also pioneered "Hybrid" technology with the Prius, which uses both a gasoline engine and an electric motor to save fuel. Today, they make every kind of car, from the tiny Yaris to the massive Land Cruiser. Toyota is a brand for people who want a car that they can trust 100%. They focus on quality and safety rather than "crazy" designs. If you buy a Toyota, you know it will start every morning for the next 20 years.`,
        dict: { "currently": "şu anda", "largest": "en büyük", "company": "şirket", "world": "dünya", "famous": "ünlü", "thing": "şey", "above": "üzerinde", "all else": "her şeyden", "reliability": "güvenilirlik", "built": "yapılmış/inşa edilmiş", "last": "dayanmak", "forever": "sonsuza dek", "Many": "birçok", "people": "insanlar", "use": "kullanır", "truck": "kamyon", "because": "çünkü", "almost": "neredeyse", "impossible": "imkansız", "break": "kırmak/bozmak", "even": "bile", "desert": "çöl", "pioneered": "öncülük etti", "Hybrid": "hibrit", "technology": "teknoloji", "uses": "kullanır", "both": "her ikisi", "gasoline": "benzin", "engine": "motor", "electric": "elektrikli", "motor": "motor", "save": "kurtarmak/tasarruf etmek", "fuel": "yakıt", "Today": "bugün", "make": "yapmak", "every": "her", "kind": "tür", "tiny": "minik", "massive": "muazzam", "brand": "marka", "want": "istemek", "trust": "güvenmek", "focus": "odaklanmak", "quality": "kalite", "safety": "güvenlik", "rather than": "den ziyade", "crazy": "çılgın", "designs": "tasarımlar", "buy": "satın almak", "know": "bilmek", "start": "başlamak/çalışmak", "morning": "sabah", "next": "gelecek", "years": "yıllar" },
        questions: [ {q:"Is Toyota the largest car company?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they famous for reliability?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Hilux truck easy to break?", a_en:"No", a_tr:"Hayır"}, {q:"Did Toyota pioneer Hybrid technology?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the Prius save fuel?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they focus on crazy designs?", a_en:"No", a_tr:"Hayır"}, {q:"Can you trust a Toyota?", a_en:"Yes", a_tr:"Evet"} ]
    }],
    "21_Volkswagen.mp3": [{
        text: `Volkswagen means "The People's Car" in German. The company was started to make a car that every family could afford. Their first car was the Beetle, which became the most famous car in history and a symbol of the 1960s. After the Beetle, they made the Golf, which is the perfect "hatchback" and has been a top-seller for 50 years. Volkswagen is a massive group that now owns many other brands like Audi and Porsche. VW cars are known for being very solid and having a "premium" feel even though they are not as expensive as a Mercedes. They are currently spending billions of dollars to become a leader in electric cars with their "ID" series. Volkswagen is a brand that represents the heart of the European car industry.`,
        dict: { "means": "anlamına gelir", "People's": "halkın", "German": "Almanca", "company": "şirket", "started": "başlatıldı", "make": "yapmak", "every": "her", "family": "aile", "afford": "gücü yetmek", "first": "ilk", "became": "oldu", "most": "en", "famous": "ünlü", "history": "tarih", "symbol": "sembol", "After": "sonra", "made": "yaptı", "perfect": "mükemmel", "top-seller": "en çok satan", "years": "yıllar", "massive": "muazzam", "group": "grup", "now": "şimdi", "owns": "sahiptir", "many": "birçok", "other": "diğer", "brands": "markalar", "known": "bilinen", "solid": "sağlam", "having": "sahip olma", "premium": "birinci sınıf", "feel": "his", "even though": "olmasına rağmen", "expensive": "pahalı", "currently": "şu anda", "spending": "harcama", "billions": "milyarlarca", "dollars": "dolarlar", "become": "olmak", "leader": "lider", "electric": "elektrikli", "series": "seri", "represents": "temsil eder", "heart": "kalp", "European": "Avrupalı", "industry": "endüstri" },
        questions: [ {q:"Does Volkswagen mean The People's Car?", a_en:"Yes", a_tr:"Evet"}, {q:"Was their first car the Beetle?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Golf a top-seller?", a_en:"Yes", a_tr:"Evet"}, {q:"Does Volkswagen own Audi and Porsche?", a_en:"Yes", a_tr:"Evet"}, {q:"Are VW cars very solid?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they spending billions on electric cars?", a_en:"Yes", a_tr:"Evet"}, {q:"Does VW represent the heart of the European industry?", a_en:"Yes", a_tr:"Evet"} ]
    }]
};
